### ISSUE TITLE
Symbols.tex not parsed by pandoc

### ISSUE THREAD

**Issue by mfioretti** [mathlex/mathlex#11]
As per subject, with pandoc 2.9.2.1, Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5

this command:

` pandoc mathlex-master/doc/Symbols.tex  -f latex -t html  -o ~/mathlexdoc.html`

yelds this error:

`
Error at "source" (line 169, column 18):
expecting \end{table}
    \end{tabular}
                 ^
`

**Comment by komputerwiz** [comment]
I have not tried to do any conversion with Pandoc, but I was just able to build the TeX file builds with MacTeX now. I presume it will work fine in other TeX environments as well:

```bash
latexmk -pdf Symbols.tex
```

The output of the above command is attached.
[Symbols.pdf](https://github.com/mathlex/mathlex/files/11617507/Symbols.pdf)

**Comment by mfioretti** [comment]
thanks for the symbols list and copy of the thesis, Matthew!

**Comment by mfioretti** [comment]
thanks for the symbols list and copy of the thesis, Matthew!
